//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassificationRule) DeepCopyInto(out *ClassificationRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassificationRule.
func (in *ClassificationRule) DeepCopy() *ClassificationRule {
	if in == nil {
		return nil
	}
	out := new(ClassificationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClassificationRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassificationRuleList) DeepCopyInto(out *ClassificationRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClassificationRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassificationRuleList.
func (in *ClassificationRuleList) DeepCopy() *ClassificationRuleList {
	if in == nil {
		return nil
	}
	out := new(ClassificationRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClassificationRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassificationRuleSpec) DeepCopyInto(out *ClassificationRuleSpec) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(MatchCriteria)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassificationRuleSpec.
func (in *ClassificationRuleSpec) DeepCopy() *ClassificationRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ClassificationRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassificationRuleStatus) DeepCopyInto(out *ClassificationRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassificationRuleStatus.
func (in *ClassificationRuleStatus) DeepCopy() *ClassificationRuleStatus {
	if in == nil {
		return nil
	}
	out := new(ClassificationRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonMatchCriteria) DeepCopyInto(out *CommonMatchCriteria) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonMatchCriteria.
func (in *CommonMatchCriteria) DeepCopy() *CommonMatchCriteria {
	if in == nil {
		return nil
	}
	out := new(CommonMatchCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMatchCriteria) DeepCopyInto(out *DeploymentMatchCriteria) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMatchCriteria.
func (in *DeploymentMatchCriteria) DeepCopy() *DeploymentMatchCriteria {
	if in == nil {
		return nil
	}
	out := new(DeploymentMatchCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchCriteria) DeepCopyInto(out *MatchCriteria) {
	*out = *in
	if in.CommonMatch != nil {
		in, out := &in.CommonMatch, &out.CommonMatch
		*out = new(CommonMatchCriteria)
		(*in).DeepCopyInto(*out)
	}
	if in.PodMatch != nil {
		in, out := &in.PodMatch, &out.PodMatch
		*out = new(PodMatchCriteria)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeMatch != nil {
		in, out := &in.NodeMatch, &out.NodeMatch
		*out = new(NodeMatchCriteria)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentMatch != nil {
		in, out := &in.DeploymentMatch, &out.DeploymentMatch
		*out = new(DeploymentMatchCriteria)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchCriteria.
func (in *MatchCriteria) DeepCopy() *MatchCriteria {
	if in == nil {
		return nil
	}
	out := new(MatchCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMatchCriteria) DeepCopyInto(out *NodeMatchCriteria) {
	*out = *in
	if in.ArchLabels != nil {
		in, out := &in.ArchLabels, &out.ArchLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OSLabels != nil {
		in, out := &in.OSLabels, &out.OSLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMatchCriteria.
func (in *NodeMatchCriteria) DeepCopy() *NodeMatchCriteria {
	if in == nil {
		return nil
	}
	out := new(NodeMatchCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMatchCriteria) DeepCopyInto(out *PodMatchCriteria) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMatchCriteria.
func (in *PodMatchCriteria) DeepCopy() *PodMatchCriteria {
	if in == nil {
		return nil
	}
	out := new(PodMatchCriteria)
	in.DeepCopyInto(out)
	return out
}
